### ISSUE TITLE
Navigating to my-data results in a "Backend failure"

### ISSUE THREAD

**Issue by hodie** [RMI-PACTA/app#208]
When I (signed in, independent of browser) navigate to `https://pacta.dev.rmi.siliconally.dev/en/my-data` I get an empty page that only says "Backend call failure" with the console showing a 500.

cc @bcspragu @jdhoffa creating this bug to track the behavior discussed in #205

**Comment by bcspragu** [comment]
This is now fixed. The TL;DR is undeployed configuration changes caused the backend to crash on start-up

Longer answer:

Looking in the Azure logs, I saw:

```
2024/08/13 18:16:29 failed to parse secrets: failed to parse runner config: no runner_config.images.runner_name was provided
```

This indicates that the service is missing secrets it needs to run. Those secrets were introduced in https://github.com/RMI-PACTA/app/pull/182, and its corresponding Terraform change in https://github.com/RMI/terraform/pull/31, but those changes weren't deployed at the time.

Then, on July 10th, I deployed a fresh version of the app ([GH run](https://github.com/RMI-PACTA/app/actions/runs/9878878800)), which importantly **does not** deploy Terraform, so the app was updated to use secrets that hadn't been deployed yet.

The fix was just me deploying the latest Terraform changes, which had already been checked in.
