### ISSUE TITLE
Parsing Input/Output Coorelation

### ISSUE THREAD

**Issue by gbdubs** [RMI-PACTA/app#75]
In the meeting ~1 week ago, we discussed this problem:

The parsing image takes in a folder (containing potentially multiple files), and parses into (potentially multiple) output portfolios. This means we don't have (a) a mapping between input files + output portfolios, and (b) we lack a good name for the output portfolios.

Ideally, alongside the output portfolios, the parsing image would create a JSON file (or similar) with a structure like:

```
[
  {
     "output_portfolio_file_name": "uuid-1.txt",
     "number_of_elements": 123, // Or something similar + nonsensitive to help distinguish at a glance.
     "portfolio_name": "the name of the portfolio from the file"
      "input_file_name": "path_of_file_derived_from.txt"
   } ...
]
```

@AlexAxthelm Could you add something like this to the parsing image? Without it we're stuck naming portfolios UUIDs, which is not ideal from the user's perspective.

**Comment by hodie** [comment]
Oh yeah 100% agree that this should be within the image. I don't want multiple systems parsing the file (and potentially with differing results). My point was more that this logic should be used for all files/portfolios, not just the ones that have multiple portfolios in one file.

**Comment by gbdubs** [comment]
OK great - same page.

**Comment by cjyetman** [comment]
FYI, the `Portfolio.Name` column is/should be optional. It is only there to facilitate multi-portfolio CSVs.

**Comment by gbdubs** [comment]
Hodie, that all sounds good to me - we have a strongly unique ID that we assign during upload that is opaque to the user and globally unique, and then we have the user-settable (and user changeable) portfolio name. Our system will almost exclusively deal with the ID, but the UI will almost exclusively use the Name. 

It also sounds like we're on the same page w/r/t initial naming: if there are multiple portfolio_names in a file, use that. If there are no portfolio_names in a file use the file name sans extension.

@AlexAxthelm @cjyetman Could y'all work on providing us with that mapping when you get the chance? Once we have that we'll have the portfolio upload + parsing + standardization process done.

**Comment by AlexAxthelm** [comment]
@gbdubs for the metadata JSON, I'm running into a few issues that are proving thornier than expected.
(cc @cjyetman)

# Issue 1: undefined portfolio names
Portfolios may not have a "portfolio name" defined in the file, or there may be multiple (logical) portfolios that have the same name. In these cases, I can create a portfolio name based on the file name, but I don't know if that's necessarily the way we want to go (cc @hodie). 

For example

## Example 1
```csv
"isin","market_value","currency"
"GB0007980591",10000,"USD"
```

if this was `foo.csv`, then we would get `<uuid>.csv` out, and the json would would be something like 

```json
[{
  "portfolio_name": "foo"
  ...
}]
```

## Example 2
```csv
Investor.Name,Portfolio.Name,ISIN,MarketValue,Currency
Investor A,Portfolio A,GB0007980591,10000,USD
Investor B,Portfolio A,GB0007980591,10000,USD
```
if this was `foo.csv`, then we would get `<uuid>.csv` out, and the json would would be something like 

```json
[
  {
    "portfolio_name": "Portfolio A - Investor A"
    ...
  },
  {
    "portfolio_name": "Portfolio A - Investor B"
    ...
  }
]
```

this one is probably okay, but I feel a little weird putting the investor name in the portfolio name field (I might be a bit paranoid on this though). Another option would be to do simple sequencing (`foo-1`, `foo-2`), but that makes it difficult/impossible to tie back to the original contents (which is both the point and the problem).

# Issue 2: JSON structure
Looking at the JSON sample you provided above, it looks like your working assumption is something along the lines of 
```json
[
  {exported-portfolio-1},
  {exported-portfolio-2},
  {exported-portfolio-3},
  ...
]
```

Would it be okay to change the top-level structure to center the input files as the grain? My thinking here is that in the case of an export failure, we can add diagnostic messages for the user, even though there isn't a exported portfolio.
## Format 1:
```json
[
  {
    "input_filename": "1.csv",
    "output_files": [
      {portfolio-1},
      {portfolio-2}
    ]
  },
{
    "input_filename": "2.csv",
    "output_files": [
      {portfolio-3},
    ],
    "warnings": [
      "extra column 'notes' detected. This information will not be available in PACTA"
    ]
  },
  {
    "input_filename": "3.csv",
    "output_files": [],
    "errors": [
      "Required column 'ISIN' not found.",
      "No holdings data found in file"
    ]
  },
]
```

## Format 2: Separate files

Alternately, we could have a `portfolios.json` file with the metadata for exported portfolios, and then a `messages.json` that has all the info about failed exports


# Issue 3: Non-unique portfolio names

Since the parser that I'm writing is stateless, there isn't a way to check if a user has already created a portfolio with that name before. Example here is uploading a portfolio with some name, and then 6 months later uploading a file with the same name (same or different contents). Do we have a way in the UI for the user to distinguish between them?

**Comment by gbdubs** [comment]
Sorry Alex, I clearly missed your last post somehow. I think we're now on the same page as of [the doc we just talked about yesterday](https://docs.google.com/document/d/17cWg1Ist3hFiwFC6cLBhXbxL7MiEIwsFAM5Iywj_cEk/edit). Does that match your understanding? Can we close this out?

**Comment by cjyetman** [comment]
> ## Example 2
> ```
> Investor.Name,Portfolio.Name,ISIN,MarketValue,Currency
> Investor A,Portfolio A,GB0007980591,10000,USD
> Investor B,Portfolio A,GB0007980591,10000,USD
> ```
> 
> if this was `foo.csv`, then we would get `<uuid>.csv` out, and the json would would be something like
> 
> ```json
> [
>   {
>     "portfolio_name": "Portfolio A - Investor A"
>     ...
>   },
>   {
>     "portfolio_name": "Portfolio A - Investor B"
>     ...
>   }
> ]
> ```
> 
> this one is probably okay, but I feel a little weird putting the investor name in the portfolio name field (I might be a bit paranoid on this though). Another option would be to do simple sequencing (`foo-1`, `foo-2`), but that makes it difficult/impossible to tie back to the original contents (which is both the point and the problem).

I know I'm late to the party, but... the `Investor.Name`/`investor_name` column is/should be optional too. It's not used by the PACTA code at all, it's a holdover from former times.

Additionally, I can't think of any use case where a multi-portfolio run would have different `Investor.Name`/`investor_name` values, at least not in the way it was ever intended to work on the web app. `Investor.Name` effectively equals <username>.

**Comment by AlexAxthelm** [comment]
@cjyetman I think this is a discussion for another repo, but in the 3/5 column layouts, that's accurate. If we accept 4 column portfolios, then the 4th column could be either investor name or portfolio name. It's not hard to imagine a situation where someone working as an outside analyst would have multiple portfolios from different investors.

In any case, `workflow.portfolio.parsing` writes the 3-column version to csv, and the investor and portfolio names are captured in the metadata json alongside.
