### ISSUE TITLE
Portfolio grouping structure

### ISSUE THREAD

**Issue by AlexAxthelm** [RMI-PACTA/app#82]
For "grouped" portfolios (logical composites of multiple real portfolios), I see two main ways we could approach this:

1. The app handles the grouping, and sends a single portfolio object to the PACTA image, which returns a single PACTA report. This would require some CSV processing on the app's part
2. Whenever there are multiple portfolios exposed to the PACTA image (mounted in), it combines them all into a single portfolio in-app, and emits a single report. This is my preferred option, since it keeps all that logic in the PACTA image.

Combining the CSVs is the easy part, since those should be standardized after upload. The trickier part will be in managing the portfolio parameters, and keeping the rules about which portfolios can be grouped or not aligned.

For example, we probably shouldn't allow portfolios with different holdings dates to be grouped, or maybe portfolios that are not attached to the same initiative.

I'm thinking that the easiest way to handle this would be to have the app handle the lgoic on grouping portfolios, and pass in a single set of portfolio parameters, and expose the relevant portfolios via volume mount

So if a "normal" (ungrouped) portfolio has parameters along the line of
```json
{
  "name": "my cool portfolio",
  "holdingsDate": 20231231,
  "initiatitve": "GENERAL",
  ...
}
```

a grouped portfolio might have something like:
```json
{
  "name": "my grouped portfolio",
  "portfolios": [
    "54a66368-7388-4e27-9cce-c0dc3d169d64",
    "efb9110b-4d35-4600-94f9-769f20938555",
    "d824c50f-96aa-47d0-984a-4fc7873cb038",
    "17467439-142f-4314-b32d-cc8533f10ad0"
  ],
  "holdingsDate": 20231231,
  "initiatitve": "GENERAL",
  ...
}
```

@gbdubs @bcspragu do you have any preferences here?

**Comment by AlexAxthelm** [comment]
cc @cjyetman @hodie

**Comment by gbdubs** [comment]
I also prefer option 2 of the two described for the same reasons you listed - we'd prefer not to be in the business of looking at bytes underlying this data at all.

We've built the grouping technology for portfolios to be as simple as possible (it's a tag-type system, which today imposes no constraints on the addition of a portfolio to a group).  #85 is the first draft of the functionality as we've gotten it proposed.

Here's what I'd recommend rather than adding a constraint on the ability of a portfolio to be added to a group. We will have a robust flow for initiating a report run. We can ensure that the holding dates (and potentially other data) align at _that_ point, and then help users either remove the offending portfolios from the group pre-run, or help them modify the offending discrepancy. Does that make sense?

Then we'd follow your recommended lead on sending in parameters for the portfolio group and ensure they line up. We might wan the portfolio entries to be an object (for future proofing, it could have ID, name, etc) but other than that LGTM.

**Comment by AlexAxthelm** [comment]
This sounds good to me
